trigger:
  - main
  - develop
  - refs/tags/*

pr:
  - main
  - develop

variables:
  BASE_VERSION: 1.7.1
  PREVIEW_LABEL: 'ci'
  BUILD_NUMBER: $[counter(format('{0}_{1}_{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['Build.SourceBranch']), 1)]
  NUGET_VERSION: $[format('{0}-{1}.{2}', variables['BASE_VERSION'], variables['PREVIEW_LABEL'], variables['BUILD_NUMBER'])]
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH_NAME: $(Build.SourceBranchName)
  AREA_PATH: 'DevDiv\Xamarin SDK\Build and Tools'

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      refs: refs/heads/dev/bond/eo-pools     # UNDONE: DO NOT MERGE TO MAIN
      endpoint: xamarin

stages:
  - stage: build
    displayName: Build Library
    jobs:
      - template: .ci/build.yml@components
        parameters:
          windowsAgentPoolName: MAUI-DevDiv
          windowsImage: ''
          areaPath: 'DevDiv\Xamarin SDK'
          masterBranchName: 'main'
          preBuildSteps:
            - pwsh: |
                $pr = "pr." + $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
                $nuget = $env:BASE_VERSION + "-" + $pr + "." + $env:BUILD_NUMBER
                Write-Host "Preview label: $pr"
                Write-Host "NuGet version: $nuget"
                Write-Host "##vso[task.setvariable variable=PREVIEW_LABEL]$pr"
                Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$nuget"
              displayName: Use a special preview label for PRs
              condition: eq(variables['Build.Reason'], 'PullRequest')
            - pwsh: |
                $tagVersion = $env:BUILD_SOURCEBRANCHNAME
                Write-Host "Tag version: $tagVersion"
                Write-Host "##vso[task.setvariable variable=NUGET_VERSION]$tagVersion"
              displayName: Override version for tags
              condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
            - pwsh: |
                Write-Host "##vso[build.updatebuildnumber]$env:NUGET_VERSION"
              displayName: Update the build number with a more readable one

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - stage: signing
      displayName: Sign Artifacts
      dependsOn: [ 'build' ]
      jobs:
        - template: sign-artifacts/jobs/v2.yml@internal-templates
          parameters:
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - stage: sbom
      displayName: 'Software Bill of Materials'
      ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
        dependsOn: [ 'build' ]
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        dependsOn: [ 'signing' ]
      jobs:
      - template: compliance/sbom/job.v1.yml@internal-templates             # Software Bill of Materials (SBOM): https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/ado-sbom-generator
        parameters:
          artifactNames: ['nuget']
          packageName: 'Xamarin Essentials'
          packageFilter: '*.nupkg'

  - stage: devicetests
    displayName: Device Tests
    dependsOn: []
    jobs:
      - job: devicetests_uwp
        displayName: UWP
        # skip for now
        condition: false
        pool:
          vmImage: windows-2019
        steps:
          - script: 'certutil -importpfx $(Build.SourcesDirectory)\DeviceTests\DeviceTests.UWP\DeviceTests.UWP_TemporaryKey.pfx'
            displayName: 'Run certutil'
          - powershell: |
              cd DeviceTests
              .\build.ps1 --target=test-uwp-emu --settings_skipverification=true --verbosity=diagnostic
            displayName: 'Run Device Tests - UWP'
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: XUnit
              testResultsFiles: '**/xunit-*.xml'
              testRunTitle: 'Device Tests - UWP'

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_ios
          runChecks: false
          displayName: iOS
          publishOutputSuffix: '-ios'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-ios-emu
          xharness: '1.0.0-prerelease.21620.1'

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_android_api_21
          runChecks: false
          displayName: Android API 21
          publishOutputSuffix: '-android21'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-android-emu
          cakeExtraArgs: --avd-target="`"system-images;android-21;google_apis;x86`""
          preBuildSteps:
            - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-21;google_apis;x86\""
              displayName: Install the Android emulators

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_android_api_22
          runChecks: false
          displayName: Android API 22
          publishOutputSuffix: '-android22'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-android-emu
          cakeExtraArgs: --avd-target="`"system-images;android-22;google_apis;x86`""
          preBuildSteps:
            - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-22;google_apis;x86\""
              displayName: Install the Android emulators

#       - template: .ci/build.yml@components
#         parameters:
#           windowsImage: windows-2019
#           name: devicetests_android_api_23
#           runChecks: false
#           continueOnError: true
#           displayName: Android API 23
#           publishOutputSuffix: '-android23'
#           areaPath: $(AREA_PATH)
#           verbosity: diagnostic
#           cakeFile: DeviceTests/build.cake
#           cakeTarget: test-android-emu
#           cakeExtraArgs: --avd-target="`"system-images;android-23;google_apis;x86`""
#           preBuildSteps:
#             - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-23;google_apis;x86\""
#               displayName: Install the Android emulators

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_android_api_24
          runChecks: false
          displayName: Android API 24
          publishOutputSuffix: '-android24'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-android-emu
          cakeExtraArgs: --avd-target="`"system-images;android-24;google_apis;x86`""
          preBuildSteps:
            - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-24;google_apis;x86\""
              displayName: Install the Android emulators

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_android_api_26
          runChecks: false
          displayName: Android API 26
          publishOutputSuffix: '-android26'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-android-emu
          cakeExtraArgs: --avd-target="`"system-images;android-26;google_apis;x86`""
          preBuildSteps:
            - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-26;google_apis;x86\""
              displayName: Install the Android emulators

      - template: .ci/build.yml@components
        parameters:
          windowsImage: windows-2019
          name: devicetests_android_api_29
          runChecks: false
          displayName: Android API 29
          publishOutputSuffix: '-android29'
          areaPath: $(AREA_PATH)
          verbosity: diagnostic
          cakeFile: DeviceTests/build.cake
          cakeTarget: test-android-emu
          cakeExtraArgs: --avd-target="`"system-images;android-29;google_apis;x86`""
          preBuildSteps:
            - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-29;google_apis;x86\""
              displayName: Install the Android emulators

      # - template: .ci/build.yml@components
      #   parameters:
      #     windowsImage: windows-2019
      #     name: devicetests_android_api_30
      #     runChecks: false
      #     displayName: Android API 30
      #     publishOutputSuffix: '-android30'
      #     areaPath: $(AREA_PATH)
      #     verbosity: diagnostic
      #     cakeFile: DeviceTests/build.cake
      #     cakeTarget: test-android-emu
      #     cakeExtraArgs: --avd-target="`"system-images;android-30;google_apis;x86`""
      #     preBuildSteps:
      #       - bash: sh -c "echo \"y\" | $ANDROID_HOME/tools/bin/sdkmanager \"system-images;android-30;google_apis;x86\""
      #         displayName: Install the Android emulators
